name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Print Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run tests with race detector
        run: go test ./... -race -cover

      - name: Check formatting
        run: |
          gofmt -l . | grep . && echo "gofmt found unformatted files" && exit 1 || true
